### PR TITLE
Issue133 non utf8 headers

### LINKED ISSUE #133: non UTF8 header seen by sarrac on flow_test (cpump)
running flow test suite, from  cpump_pelle_dd1_f04_01.log

```
2023-12-05 19:19:00,582 [WARNING] skipping non UTF8 headers: amount: 7, this one: 3, kind:73
2023-12-05 19:19:00,582 [INFO] received: { "pubTime":"20231206001857.646", "baseUrl":"https://hpfx.collab.science.gc.ca", "relPath":"/20231206/WXO-DD/.hello_weather/observations/03/03048.1.OBS.PUB.FR.SPX~20231206000500-20231206020500-1427", "topic":"v02.post.20231206.WXO-DD.hello_weather.observations.03", "identity":{  "method" : "md5", "value" : "aOhJn7exRUsa1TAq1lMZlg=="  } , "mtime":"20231206001900.53", "atime":"20231206001900.53", "mode":"0666", "size":"96940", "to_clusters":"DDI,DDSR", "sundew_extension":"DMS:CMC:WXR-TRANSCODER-OBS-DATAMART-IVR:AUDIO"}
```

### PR DESCRIPTION
**Pull request by petersilva**
closes #133 

parse numeric headers (formerly just printed an warning message, and ... key thing, skipped the rest of the headers... resulting in potentially corrupted messages.  So now parse them normally and keep reading headers so we get them all.

### CODE REVIEW

**Comment by andreleblanc11** [comment]
The changes look to make sens

**Comment by andreleblanc11** [comment]
The `shim_copy_strip_slash` test is failing on the flow tests. This PR doesn't look to have any impact on that though?

**Comment by petersilva** [comment]
yeah, that's weird... the test_shim tests used to completely work on github, but for the last few days, it has started failing.  I don't know why.  I triggerred the same Action manually, and now tags that passed before don't pass.

**Comment by petersilva** [comment]
OK, was working on another branch about getting mirroring tests to work when the directory being mirrored is accessed via a symlinked path (so `realpath .` != `pwd` )

Mirroring requires understanding and transformation of absolute paths, which means to the real location of files changes things.  In HPC clusters, such symlinked directories are common, and so the use case needs to be addressed.

The apparent cause in the test failures originally was message like "post outside of post_baseDir"  which will show up when the real-directory and directory path being used do not match, which is why the work on both problems was joined together.

Many changes related settings like post_baseDir, and another problem being resolved in the symlink/HPC case was that ~/test was used, but if the directory being used for testing is outside $HOME... so further adjustments needed.

One source of confusion/complication is if a post_baseDir is supplied as, say ~/kkk and ~ is actually symlinked, then need to apply realpath resolution to the post_baseDir settings.  Settings in the config files were adjusted to reflect what they should be to reflect proper setting of post_baseDir.

As initial work, removed tests that continue to fail after initial adjustments were done.  T

### tests that pass:

* test_shim_post - creating effective posts.
* test_copy_strip - copy using the strip argument (which, I think is what CMOI mirroring does.)
* test_copy_mirror - copy using a source and dest directories (a "normal" way to do the copies.)

### tests that still do not pass:

* test_shim_copy_mirror_sftp -- using SFTP urls instead of file for URL, processing of baseDir different.
* test_shim_copy_strip_slash -- 
* test_shim_copy_baseDir

investigation continues.

**Comment by petersilva** [comment]
At this point nobody is comfortable merging this pele-mele of changes.
will build some other PR's via cherry picking the corpse of this one.

**Pull request closed without merging**
