### PR TITLE
#28 Arbitrary checksum support and xattr save on post

### PR DESCRIPTION
**Pull request by msaraga**
Tested using a local setup: 
 - sr_config local xattr setting
 - sr_config header processing
 - sr_cpost arbitrary checksum option as sum header
 - cpump transmission
They all appear to work as they should.
Unit tests will be included in unit test overhaul (for another branch and pull request, this is getting to big)
Flow test passed!

### CODE REVIEW

**Comment by petersilva** [comment]
* python implementation has attributes with sr_ prefix as mentioned in original issue description.  

* mtime should reflect modification time of file, not call time of sr_cpost   lstat + sb.st_mtim as arg.

* when called with -sum a,hoho it dumps core.

**Comment by msaraga** [comment]
talked with peter: deprecating `-header sum=a,WHATEVER`, using `-sum a,WHATEVER` syntax instead

**Comment by petersilva** [comment]
@msaraga can you write something here to explain why the issue has been closed.  We had a lot of discussion, and I lost track.

**Comment by msaraga** [comment]
The issue hasn't been closed, only the pull request.
Development of the feature is still very much in progress!
Will reopen once I have something tested and ready for merging.

**Comment by petersilva** [comment]
ok fine. thanks!

**Pull request closed without merging**
