### PR TITLE
Syscall auto-generation

### PR DESCRIPTION
**Pull request by reidsunderland**
Adds a script to automatically generate syscall passthrough code, and adds passthroughs for hopefully almost all of the syscalls :)

I'm creating this as a draft for now, I'll convert it to "ready for review" once I've done a bit more testing.

### CODE REVIEW

**Comment by reidsunderland** [comment]
rename and renameat (not 2) are currently being passed through, so I'll make another commit to handle those just like renameat2

**Comment by reidsunderland** [comment]
I would also happily take suggestions on how to better separate out the syscall code into a separate file. I just wanted to get it working and tested first, so dumped it all into libsr3shim.c.

**Review by petersilva — APPROVED** [review]
This is Sick!  Great work!
If there's anything wrong with it, it's better to fix it later... commit early, commit often.

**Comment by petersilva** [comment]
The PR is in draft... is it ready to merge?

**Comment by reidsunderland** [comment]
I was working on adding the code to ensure that messages get posted for these syscalls:

```
close
dup2
dup3
link
linkat
mkdir
mkdirat
rmdir
symlink
symlinkat
truncate
unlink
unlinkat
```

I think it's ready.

**Pull request merged**
