### PR TITLE
Issue14: strip option implementation (numerical only for now)

### PR DESCRIPTION
**Pull request by msaraga**
Tested locally, everything seems to work!
Moving on to regex strip now!

### CODE REVIEW

**Comment by petersilva** [comment]
ugh... I'm very confused... this patch does what it should, but I compared it to the python, and the python does something different than what I thought it did.  if I do:

```
sr_post -strip 3 -c local_post.conf -path `pwd`/uthash.h
result is:
019-03-22 21:37:04,022 [INFO] post_log notice=20190323013704.021430 sftp://sarra_test@localhost /home/peter/src/sarrac/uthash.h headers={'toto': 'pig', 'to_clusters': 'localhost', 'rename': '/sarrac/uthash.h', 'mtime': '20180411044127', 'atime': '20190323012747.445404768', 'mode': '644', 'parts': '1,58925,1,0,0', 'sum': 'd,3bc830cf226e2de0d86b7141eb6cded7'}

```
It kept the original path the same, but applies the strip to a **rename** header...   
with this patch, if I do: 
```
./sr_cpost -strip 3 -c local_post.conf -path `pwd`/uthash.h

2019-03-22 21:37:49,189 [INFO] published: 20190323013749.189246918 sftp://sarra_test@localhost src/sarrac/uthash.h topic=v02.post.home.peter.src.sarrac sum=d,3bc830cf226e2de0d86b7141eb6cded7 source=tsource to_clusters=localhost from_cluster=localhost mtime=20180411044127.0 atime=20190323012747.445404674 mode=0644 parts=1,58925,1,0,0 toto=pig
```

The C and the python are supposed to work the same as much as that is possible. So while the patch is correct in that it does what was asked for, I'm worrying that the specification was wrong.  

also you might want to do a pull on issue14, I had to futz with it to get split declared in config.h (the commenting work messed up the ability to merge.)

**Comment by msaraga** [comment]
I ve updated the strip to work like the python version, let me know what you think

**Comment by petersilva** [comment]
close but no cigar...  you are creating the rename header prior to application of the post_base_dir setting.
so the result is still different from python, which applies strip after the removal of post_base_dir.

It's obvious if I set post_base_dir /home/peter, and then:

sr_post -strip 1 -c local_post.conf -p `pwd`/uthash.h

gives:
2019-03-28 01:43:21,490 [DEBUG] Published2: '20190328054321.489618 http://localhost:8808 /src/sarrac/uthash.h' atime=20190328053852.241724253 mode=644 mtime=20190325025633.686447859 parts=1,58925,1,0,0 rename=/sarrac/uthash.h sum=d,3bc830cf226e2de0d86b7141eb6cded

but sr_cpost gives:

2019-03-28 01:42:50,366 [DEBUG] sr_cpost file2message start with: /home/peter/src/sarrac/uthash.h sb=0x7ffd49ab68c0 islnk=0, isdir=0, isreg=1
2019-03-28 01:42:50,367 [INFO] published: 20190328054250.366648969 http://localhost:8808 /src/sarrac/uthash.h topic=v02.post.src.sarrac sum=d,3bc830cf226e2de0d86b7141eb6cded7 source=tsource to_clusters=localhost from_cluster=localhost mtime=20190325025633.686447752 atime=20190328053852.241724184 mode=0644 parts=1,58925,1,0,0 rename=/peter/src/sarrac/uthash.h toto=pig

**Comment by msaraga** [comment]
fixed

**Comment by petersilva** [comment]
Merged!

**Pull request merged**
