### PR TITLE
Issue141 2nd try

### LINKED ISSUE #141: HPC mirroring... sr3_cpost from within a tree being mirrored.
have a user report of strange failures in a supercomputer jobs that is failing to run sr3_cpost when inside a job that has the shim library active.  start by trying to reproduce.

```

git clone https://github.com/MetPX/sr_insects insects
cd insects/static*
./flow_setup.sh declare


```
results in:

```
blacklab% sr3 status 'post/*'
status: 
Component/Config                         Processes   Connection        Lag                Rates                                        
                                         State   Run Retry  msg data   LagMax  LagAvg  %rej     pubsub   messages     RxData     TxData 
                                         -----   --- -----  --- ----   ------  ------  ----   --------       ----     ------     ------ 
post/shim_f63                            stop    0/0          -          -         -     -          -        -
post/t_dd1_f00                           stop    0/0          -          -         -     -          -        -
post/t_dd2_f00                           stop    0/0          -          -         -     -          -        -
post/test2_f61                           stop    0/0          -          -         -     -          -        -
      Total Running Configs:   0 ( Processes: 0 missing: 0 stray: 0 )
                     Memory: uss:0 Bytes rss:0 Bytes vms:0 Bytes 
                   CPU Time: User:0.00s System:0.00s 
	   Pub/Sub Received: 0 msgs/s (0 Bytes/s), Sent:  0 msgs/s (0 Bytes/s)
	      Data Received: 0 Files/s (0 Bytes/s), Sent: 0 Files/s (0 Bytes/s) 
blacklab% 

```

cd into metpx-sr3c source dir:
```

export LD_PRELOAD="`pwd`/libsr3shim.so.1.0.0"
export SR_POST_CONFIG=~/.config/sr3/post/shim_f63.conf
bash # start a subshell with the shim active.
cd ~/sarra_de*
mkdir hoho

```
now an actual post:

```
blacklab% /bin/echo hoho >lala* 
2024-01-18 17:56:53,470 [INFO] logEvents option not implemented, ignored.
2024-01-18 17:56:53,470 [INFO] tls_rigour option not implemented, ignored.
2024-01-18 17:56:53,470 [INFO] amqp_consumer option not implemented, ignored.
2024-01-18 17:56:53,479 [INFO] published: { "pubTime":"20240118225653.47458286", "baseUrl":"ftp://anonymous@localhost:2121", "relPath":"hoho/lala_wrapper.txt", "topic":"v03.post.hoho", "identity":{  "method" : "sha512", "value" : "V/BeoaZp+hh0CbopUiR/1kckdUspp4oAnsDmhZhaIXVKb3gGPB5lrT62enDtl5lxQ/e+vO9GsuoRH1\nY+rlGhxQ=="  } , "mtime":"20240118225653.46532026", "atime":"20240118224459.97378987", "mode":"0664", "size":"5"}
blacklab% 

```
that was produced by forking an echo... I noticed built-in echo had no effect... harrumph.
next try a cpost

```

blacklab% sr3_cpost -c ~/.config/sr3/post/t_dd1_f00.conf -p lala*
2024-01-18 17:58:27,039 [INFO] logEvents option not implemented, ignored.
2024-01-18 17:58:27,039 [INFO] tls_rigour option not implemented, ignored.
2024-01-18 17:58:27,039 [INFO] amqp_consumer option not implemented, ignored.
2024-01-18 17:58:27,040 [ERROR] Environment variable not set: SAMPLEDATA
2024-01-18 17:58:27,040 [INFO] set option not implemented, ignored.
2024-01-18 17:58:27,040 [INFO] set option not implemented, ignored.
2024-01-18 17:58:27,040 [DEBUG] sr_cpost 3.23.11p3 settings: action=foreground hostname=blacklab config_name=t_dd1_f00 log_level=6
2024-01-18 17:58:27,040 [DEBUG] 	follow_symlinks=no realpath: Adjust=0 Filter=yes Post=no
2024-01-18 17:58:27,040 [DEBUG] 	force_polling=off sleep=0 expire=86400 housekeeping=300 sanity_log_dead=450 nodupe_ttl=0 nodupe_fileAgeMin=0 nodupe_fileAgeMax=2.592e+06
2024-01-18 17:58:27,040 [DEBUG] 	cache_file=off cache_basis=path, accept_unmatch=on messageRateMax=0
2024-01-18 17:58:27,040 [DEBUG] 	fileEvents=006f directory=(null) queuename=(null) logReject=on sum=s
2024-01-18 17:58:27,040 [DEBUG] 	statehost=no v2compatRenameDoublePost=no
2024-01-18 17:58:27,040 [DEBUG] 	message_ttl=0 post_exchange=xsarra post_exchange_split=0 post_exchangeSuffix=(null)
2024-01-18 17:58:27,040 [DEBUG] 	source=A to=localhost post_baseUrl=http://localhost:8090 post_baseDir=(null)
2024-01-18 17:58:27,040 [DEBUG] 	topicPrefix=v03 post_topicPrefix=v03.post, pid=-1
2024-01-18 17:58:27,040 [DEBUG] man sr3_cpost(1) for more information
2024-01-18 17:58:27,043 [DEBUG] 3.23.11p3 connected to post broker amqp://tfeed@localhost:5672/#xsarra
2024-01-18 17:58:27,043 [DEBUG] declaring exchange amqp://tfeed@localhost:5672/#xsarra
2024-01-18 17:58:27,044 [DEBUG] sr_config_read about to open: /home/peter/.config/sr3/default.conf
2024-01-18 17:58:27,044 [INFO] logEvents option not implemented, ignored.
2024-01-18 17:58:27,044 [INFO] tls_rigour option not implemented, ignored.
2024-01-18 17:58:27,044 [INFO] amqp_consumer option not implemented, ignored.
2024-01-18 17:58:27,044 [DEBUG] sr_config_read about to open: /home/peter/.config/sr3/post/shim_f63.conf
2024-01-18 17:58:27,044 [DEBUG] sr_shim 3.23.11p3 settings: action=foreground hostname=blacklab config_name=NONE log_level=5
2024-01-18 17:58:27,044 [DEBUG] 	follow_symlinks=no realpath: Adjust=0 Filter=yes Post=no
2024-01-18 17:58:27,044 [DEBUG] 	force_polling=off sleep=0 expire=86400 housekeeping=300 sanity_log_dead=450 nodupe_ttl=0 nodupe_fileAgeMin=0 nodupe_fileAgeMax=2.592e+06
2024-01-18 17:58:27,044 [DEBUG] 	cache_file=off cache_basis=path, accept_unmatch=on messageRateMax=0
2024-01-18 17:58:27,044 [DEBUG] 	fileEvents=006f directory=(null) queuename=(null) logReject=off sum=s
2024-01-18 17:58:27,044 [DEBUG] 	statehost=no v2compatRenameDoublePost=no
2024-01-18 17:58:27,044 [DEBUG] 	message_ttl=0 post_exchange=xs_tsource_shim post_exchange_split=0 post_exchangeSuffix=(null)
2024-01-18 17:58:27,044 [DEBUG] 	source=tsource to=localhost post_baseUrl=ftp://anonymous@localhost:2121 post_baseDir=/home/peter/sarra_devdocroot
2024-01-18 17:58:27,044 [DEBUG] 	topicPrefix=v03 post_topicPrefix=v03.post, pid=-1
2024-01-18 17:58:27,044 [DEBUG] man sr3_cpost(1) for more information
2024-01-18 17:58:27,044 [DEBUG] realpath_adjust 0, /home/peter/.cache/sr3/cpost/t_dd1_f00/i01.pid -> /home/peter/.cache/sr3/cpost/t_dd1_f00/i01.pid 
2024-01-18 17:58:27,049 [DEBUG] 3.23.11p3 connected to post broker amqp://tsource@localhost:5672/#xs_tsource_shim
2024-01-18 17:58:27,049 [DEBUG] declaring exchange amqp://tsource@localhost:5672/#xs_tsource_shim
2024-01-18 17:58:27,049 [ERROR] posting outside of post_baseDir (/home/peter/sarra_devdocroot) invalid path: /home/peter/.cache/sr3/cpost/t_dd1_f00/i01.pid
2024-01-18 17:58:27,049 [INFO] cpost 3.23.11p3 config: t_dd1_f00, pid: 620464, starting
2024-01-18 17:58:27,049 [DEBUG] sr_event_mask: 006f translated to inotify_event_mask: 20003cc
2024-01-18 17:58:27,049 [DEBUG] starting polling loop pass: 0
2024-01-18 17:58:27,051 [DEBUG] v03 body={ "pubTime" : "20240118T225827.04942486", "baseUrl" : "http://localhost:8090", "relPath" : "home/peter/sarra_devdocroot/hoho/lala_wrapper.txt", "identity" : {  "method" : "sha512", "value" : "z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlOD\nJ6+SfaPg=="  }, "source" : "A", "size" : "0", "atime" : "20240118T225653.4733203", "mtime" : "20240118T225814.87772124", "mode" : "664" }  

2024-01-18 17:58:27,057 [INFO] published: { "pubTime":"20240118225827.04942486", "baseUrl":"http://localhost:8090", "relPath":"home/peter/sarra_devdocroot/hoho/lala_wrapper.txt", "topic":"v03.post.home.peter.sarra_devdocroot.hoho", "identity":{  "method" : "sha512", "value" : "z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlOD\nJ6+SfaPg=="  } , "mtime":"20240118225814.87772124", "atime":"20240118225653.4733203", "mode":"0664", "size":"0"}
2024-01-18 17:58:27,057 [DEBUG] 620464 cpost post broker closing.
2024-01-18 17:58:27,057 [DEBUG] cpost post broker closed.
2024-01-18 17:58:27,057 [DEBUG] realpath_adjust -1, /home/peter/.cache/sr3/cpost/t_dd1_f00 -> /home/peter/.cache/sr3/cpost/t_dd1_f00 
2024-01-18 17:58:27,058 [ERROR] posting outside of post_baseDir (/home/peter/sarra_devdocroot) invalid path: /home/peter/.cache/sr3/cpost/t_dd1_f00/i01.pid
2024-01-18 17:58:27,058 [DEBUG] 620464 shim post broker closing.
2024-01-18 17:58:27,058 [DEBUG] shim post broker closed.

```

The this post is clearly using the expected configuration, as the source set to A in the published message shows.  The client observed that it looked like the SR_POST_CONFIG (shim) post setting, and the posting configuration provided on the command line, seemed to be mixed... or one was applying to the other.

So far, this is working fine. haven't reproduced a thing.

### PR DESCRIPTION
**Pull request by petersilva**
close #141 

Had to change global variables into pieces of context passed to library routines... a lot of changes, but that's all it did.

### CODE REVIEW

**Comment by petersilva** [comment]
I need to test a little more... but this might do it.

**Comment by petersilva** [comment]
Added some patches, and it looks like it does the right thing now.  I asked the client to test.
not sure if we should merge now or wait for client test result.

**Comment by petersilva** [comment]
As noted by @reidsunderland we still have some multi-threading vulnerabilities... perhaps best to address. will review.

**Comment by petersilva** [comment]
The multithreading stuff is quite big... in volume... it basically means getting rid of all variables declared *static* as there is always a race condition when called by multiple threads.  I think it's better to have a separate branch for that (maybe more than one.) and merge this stuff (already >600 loc.) as is for now.  It likely solves the user's problem as-is.

**Review by reidsunderland — APPROVED** [review]
I'm good with merging this and fixing the other stuff separately

**Pull request merged**
