### PR TITLE
Issue73

### PR DESCRIPTION
**Pull request by msaraga**
#73

### CODE REVIEW

**Comment by petersilva** [comment]
the logic of DESTDIR=build.... if DESTDIR != build is ... odd... not sure why the if statement is needed, but whatever...

ran 

```
% debuild -us -uc
runs at first, after a while:

dh_install: sarrac missing files: build/lib/libsrshim*
dh_install: missing files, aborting
	install -d debian/.debhelper/generated/libsarrac-dev
	install -d debian/.debhelper/generated/libsarrac
	install -d debian/.debhelper/generated/sarrac
debian/rules:18: recipe for target 'binary' failed
make: *** [binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui failed
blacklab% 

```

Looks like the mods for RPM compatibility broke debian packaging.

**Comment by msaraga** [comment]
Hmmm that's unexpected.. I had tested `make` and `make install` directly and expected the deb to build as usual. Turns out `debuild` also sets `DESTDIR` and we were just ignoring it.
```bash
make -j1 install DESTDIR=/home/anon/sarrac/debian/tmp AM_UPDATE_INFO_DIR=no
```

**Comment by petersilva** [comment]
does RPM need to use DESTDIR? if we change the name do we get rid of the problem?  and while we are fooling with that... why the if statement (if DESTDIR == build  it does the same thing in the else clause that it does in every other case with the then clause... strange to have an if there...

**Comment by msaraga** [comment]
I have changed things up to fix the debuild issue. There are definitely much more elegant solutions... but using DESTDIR on the rpm side was the quickest solution given project priorities

**Comment by msaraga** [comment]
OK builds are now working on Ubuntu18.04, OpenSUSE15 and CentOS7, ready for further review

**Comment by petersilva** [comment]
debuild works, flow_test passes.

**Pull request merged**
