### PR TITLE
added arbitrary checksum support #45

### PR DESCRIPTION
**Pull request by msaraga**

### CODE REVIEW

**Comment by petersilva** [comment]
I´m worried about the length... in get_sumhashlen, you return a fixed value SHA512_DIGEST_LENGTH+1 for case ´a´...  nowhere else in the code is the length controlled.   The parsing uses strdup() & strcpy(),  so the string could be longer or shorter... how do you know get_sumhashlen does the right thing in all cases?

for example, it looks like it is used in sr_sumstr2hash, so if you have a short arbitrary string, it is going to copy out to that length, potentially random bytes... zeroing them out before it starts... looks pretty dangerous.

I´ll test it anyways, but won´t merge until further discussion on this.

**Comment by petersilva** [comment]
It would be fun if you ran it as is through valgrind, and see if it complains.

**Comment by petersilva** [comment]
it does pass flow test.

**Comment by msaraga** [comment]
would it be acceptable to set the arbitrary checksum length to a fixed value?
we could truncate if the provided checksum is too long, pad if it is too short and require that DMS provide us arbitrary checksums of the correct length.

**Comment by petersilva** [comment]
I don't think fixed length is good... I did it because it was possible (and I was lazy) but ideally we should adapt to any reasonable string length.   As discussed, I think 253 bytes (AMQP max minus algo and comma) but adapting the code to work with variable length strings is probably the best thing todo.
and it should be a string (no null characters allowed.)

**Comment by msaraga** [comment]
sounds like a call to `strnlen` would do the trick

**Comment by petersilva** [comment]
sounds good.

**Comment by petersilva** [comment]
I´m still a little worried about strnlen.    perhaps test it by setting it to eight characters instead of 253.
and see if it behaves sanely.   for example, there is strncpy... will it be missing a terminating null if it gets length truncated?

**Comment by petersilva** [comment]
rejecting for now... more work needed.

**Pull request closed without merging**
